// Code generated by protoc-gen-go.
// source: coin.proto
// DO NOT EDIT!

/*
Package cpb is a generated protocol buffer package.

It is generated from these files:
	coin.proto

It has these top-level messages:
	LoginRequest
	MineRequest
	LoginReply
	MineReply
*/
package cpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type LoginRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Mine request carries the same name as login
type MineRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MineRequest) Reset()                    { *m = MineRequest{} }
func (m *MineRequest) String() string            { return proto.CompactTextString(m) }
func (*MineRequest) ProtoMessage()               {}
func (*MineRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// The response message containing the assigned id and work
type LoginReply struct {
	Id   int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Work string `protobuf:"bytes,2,opt,name=work" json:"work,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// The mining response is boolean
type MineReply struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *MineReply) Reset()                    { *m = MineReply{} }
func (m *MineReply) String() string            { return proto.CompactTextString(m) }
func (*MineReply) ProtoMessage()               {}
func (*MineReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*LoginRequest)(nil), "cpb.LoginRequest")
	proto.RegisterType((*MineRequest)(nil), "cpb.MineRequest")
	proto.RegisterType((*LoginReply)(nil), "cpb.LoginReply")
	proto.RegisterType((*MineReply)(nil), "cpb.MineReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Coin service

type CoinClient interface {
	// very first message client -> server requests login details
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	// this is a request to start mining
	Mine(ctx context.Context, in *MineRequest, opts ...grpc.CallOption) (*MineReply, error)
}

type coinClient struct {
	cc *grpc.ClientConn
}

func NewCoinClient(cc *grpc.ClientConn) CoinClient {
	return &coinClient{cc}
}

func (c *coinClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/cpb.Coin/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coinClient) Mine(ctx context.Context, in *MineRequest, opts ...grpc.CallOption) (*MineReply, error) {
	out := new(MineReply)
	err := grpc.Invoke(ctx, "/cpb.Coin/Mine", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Coin service

type CoinServer interface {
	// very first message client -> server requests login details
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	// this is a request to start mining
	Mine(context.Context, *MineRequest) (*MineReply, error)
}

func RegisterCoinServer(s *grpc.Server, srv CoinServer) {
	s.RegisterService(&_Coin_serviceDesc, srv)
}

func _Coin_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpb.Coin/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coin_Mine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinServer).Mine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cpb.Coin/Mine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinServer).Mine(ctx, req.(*MineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cpb.Coin",
	HandlerType: (*CoinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Coin_Login_Handler,
		},
		{
			MethodName: "Mine",
			Handler:    _Coin_Mine_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("coin.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0xcf, 0xcc,
	0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2e, 0x48, 0x52, 0x52, 0xe2, 0xe2, 0xf1,
	0xc9, 0x4f, 0xcf, 0xcc, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9,
	0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x14, 0xb9, 0xb8,
	0x7d, 0x33, 0xf3, 0x52, 0xf1, 0x29, 0x31, 0xe0, 0xe2, 0x82, 0x1a, 0x53, 0x90, 0x53, 0x29, 0xc4,
	0xc7, 0xc5, 0x94, 0x99, 0x02, 0x96, 0x67, 0x0d, 0x62, 0xca, 0x4c, 0x01, 0xe9, 0x28, 0xcf, 0x2f,
	0xca, 0x96, 0x60, 0x82, 0xe8, 0x00, 0xb1, 0x95, 0xa4, 0xb9, 0x38, 0x21, 0x86, 0x42, 0x35, 0xe4,
	0x67, 0x83, 0x35, 0x70, 0x04, 0x31, 0xe5, 0x67, 0x1b, 0x25, 0x72, 0xb1, 0x38, 0xe7, 0x67, 0xe6,
	0x09, 0xe9, 0x72, 0xb1, 0x82, 0x8d, 0x15, 0x12, 0xd4, 0x4b, 0x2e, 0x48, 0xd2, 0x43, 0x76, 0xa9,
	0x14, 0x3f, 0xb2, 0x50, 0x41, 0x4e, 0xa5, 0x12, 0x83, 0x90, 0x16, 0x17, 0x0b, 0xc8, 0x4c, 0x21,
	0x01, 0xb0, 0x14, 0x92, 0x9b, 0xa5, 0xf8, 0x90, 0x44, 0xc0, 0x6a, 0x93, 0xd8, 0xc0, 0x81, 0x60,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x84, 0x10, 0x5b, 0x12, 0x01, 0x00, 0x00,
}
